### ISSUE TITLE
Mf skidded whole code 🥱😹

### ISSUE THREAD

**Issue by hoemotion** [ExordiumX/bypasser#3]
https://github.com/avengy/hcaptcha-bypass-discord/blob/main/hcapbypass.py

do you even have one repo which isnt skidded?

**Comment by ExordiumX** [comment]
> https://github.com/avengy/hcaptcha-bypass-discord/blob/main/hcapbypass.py
> 
> 
> 
> do you even have one repo which isnt skidded?

You're saying I can't use a public bypass to integrate with puppeteer and share for ease of use?

**Comment by hoemotion** [comment]
> > https://github.com/avengy/hcaptcha-bypass-discord/blob/main/hcapbypass.py
> > do you even have one repo which isnt skidded?
> 
> You're saying I can't use a public bypass to integrate with puppeteer and share for ease of use?

No, the only things you cant are coding and giving credits

**Comment by ExordiumX** [comment]
> > > https://github.com/avengy/hcaptcha-bypass-discord/blob/main/hcapbypass.py
> 
> > > do you even have one repo which isnt skidded?
> 
> > 
> 
> > You're saying I can't use a public bypass to integrate with puppeteer and share for ease of use?
> 
> 
> 
> No, the only things you cant are coding and giving credits

You're saying no credit is given here https://gist.github.com/ExordiumX/ef2b0f142ac96c7ddaa3aa2d71bb0120

**Comment by cChimney** [comment]
Skid 🤡

**Comment by cChimney** [comment]
scam some more kids fr
